name: Main Workflow

on:
  push:
    branches:
      - develop
      - main

jobs:
  call-node-workflow:
    uses: leonardopirss/workflow/.github/workflows/node.yml@develop
    with:
      node-version: '18'
      SVC_TOKEN: ${{ secrets.SVC_TOKEN }}
    secrets: inherit
