name: Main Workflow

on:
  push:
    branches:
      - develop
      - main

jobs:
  call-node-workflow:
    uses: leonardopirss/workflow/.github/workflows/node.yml@main
    with:
      node-version: '18'
    secrets: inherit
